name: Deploy Docs

on:
  push:
    branches:
     - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@2
      - name: Install
        run: npm install
      - name: Build and Deploy
        run: npm deploy
